src/settings/components/CreateEditRole/CreateEditRole.js, src/settings/components/CreateEditRole/CreateEditRole.test.js, src/settings/components/RoleDetails/context/RoleDetailsContext/RoleDetailsContextProvider.js
The tables are read only, the next step is to make them interactive by assigning capabilities to roles
=> View capabilities in create edit role, role details

src/hooks/useCapabilities.js, src/hooks/useCapabilities.test.js, src/settings/components/Capabilities/CapabilitiesDataType.test.js, src/settings/components/Capabilities/CapabilitiesProcedural.test.js, src/settings/components/Capabilities/CapabilitiesSection.js, src/settings/components/Capabilities/CapabilitiesSettings.test.js, src/settings/components/Capabilities/ItemActionCheckbox.js, src/settings/components/CreateEditRole/CreateRole.test.js, src/settings/components/CreateEditRole/EditRole.test.js, src/settings/components/RoleDetails/RoleDetails.test.js, src/settings/types/index.js, src/settings/utils/grouping.js, src/settings/utils/grouping.test.js, test/jest/__mock__/index.js, test/jest/__mock__/resizeObserver.mock.js
Currently, there are multiple rows for the same resource and different actions. The purpose of this PR is to group them to one row.
=> UIROLES-2: secondary sort and group capabilties by resource

CHANGELOG.md, src/hooks/useApplicationCapabilities.js, src/hooks/useCapabilities.js
Retrieve up to 5000 capabilites at once, instead of using the build-specific default of 2000. It didn't feel like raising the application-wide default was the right approach here. Swapping in a hard-coded value doesn't feel great, but doesn't necessarily feel wrong in this instance.
Refs [UIROLES-47](https://folio-org.atlassian.net/browse/UIROLES-47)
=> UIROLES-47 retrieve up to 5000 capabilities at once

CHANGELOG.md, package.json, translations/ui-authorization-roles/en.json, translations/ui-authorization-roles/en_GB.json, translations/ui-authorization-roles/en_SE.json, translations/ui-authorization-roles/en_US.json
Provide the `settings.authorization-roles.enabled` pset that allows stripes to display this module.
Refs [UIROLES-54](https://folio-org.atlassian.net/browse/UIROLES-54)
=> UIROLES-54 include settings pset

CHANGELOG.md, src/hooks/useCreateRoleMutation.js, src/settings/components/CreateEditRole/EditRole.js
- Fixes [UIROLES-62](https://folio-org.atlassian.net/browse/UIROLES-62).
- Wrong variable was used before making object comparison incorrectly detect difference in capability sets.
- Lint fix.
=> Fix error when updating only name/description for authorization role

CHANGELOG.md, src/settings/utils/grouping.js, src/settings/utils/grouping.test.js
- Fixes [UIROLES-70](https://folio-org.atlassian.net/browse/UIROLES-70)
- Results now sort first by `Application ID` and then by `Resource` which is more natural for a user to browse through
=> UIROLES-70 Add secondary sort for Resource

CHANGELOG.md, src/settings/components/RoleDetails/AccordionUsers.js, src/settings/components/RoleDetails/AccordionUsers.test.js
- Fixes [UIROLES-52](https://folio-org.atlassian.net/browse/UIROLES-52)
- Use correct property `.group` instead of `.desc` to match usage in selection modal (see: https://github.com/folio-org/ui-plugin-find-user/blob/b6031584d7c32c2e75d0f170735f5073a2e43e54/src/UserSearchView.js#L255).
=> UIROLES-52 Map object to prevent it from overwriting itself on multiple renders.

CHANGELOG.md, src/settings/components/Capabilities/ItemActionCheckbox.js
Use `<NoValue />` in place of unselected checkboxes in order to provide something more visually distinct. When many checkboxes are present, it is difficult to distinguish selected from unselected checkboxes.
Refs [UIROLES-41](https://folio-org.atlassian.net/browse/UIROLES-41)
=> UIROLES-41 use NoValue for unselected capabilities in read-only mode

CHANGELOG.md, src/settings/components/RoleDetails/RoleDetails.js
- Fixes [UIROLES-71](https://folio-org.atlassian.net/browse/UIROLES-71)
- Pull in `<ConnectedUserName>` to translate UUID to User Name.
=> UIROLES-71 Show user name instead of UUID in Role Detail page

CHANGELOG.md, src/hooks/useApplicationCapabilities.js, src/hooks/useApplicationCapabilities.test.js
**[UIROLES-60](https://folio-org.atlassian.net/browse/UIROLES-60) - Show spinner while loading capabilities/capabilitySets tables after selecting applications**
On `save and close` modal is immediately closed and loading spinners are shown on capabilities accordions.
=> UIROLES-60: handle loading state on submit select applications

CHANGELOG.md, src/settings/components/RoleDetails/RoleDetails.js
Use `<ViewMetaData>` to handle display of the metadata accordion. It knows how to handle empty values and will avoid an extra query when the `createdBy` and `lastUpdatedBy` values match. `<UserName>` is not so clever and will issue a query even when it doesn't have an id.
Refs [UIROLES-78](https://folio-org.atlassian.net/browse/UIROLES-78)
=> UIROLES-78 avoid invalid queries for /users/

src/App.test.js, src/index.js, src/settings/components/CreateEditRole/CreateRole.js, src/settings/components/CreateEditRole/CreateRole.test.js, src/settings/components/CreateEditRole/EditRole.js, src/settings/components/CreateEditRole/EditRole.test.js, src/settings/components/RoleDetails/AccordionUsers.js, src/settings/components/RoleDetails/RoleDetails.js, src/settings/components/RoleDetails/RoleDetails.test.js, src/settings/components/SettingsPage/SettingsPage.js, src/settings/components/SettingsPage/SettingsPage.test.js
Refs [UIROLES-73](https://folio-org.atlassian.net/browse/UIROLES-73).
Instead of using variable `users` which is array of object that includes `id`, the variable `usersData` was provided as [] { fullName, patronGroup }.
This PR also fixes a small issue introduced by UIROLES-46. The basename={baseUrl} provided to the Router component prevents users from navigating out of the basename, which is necessary for AccordionUsers using TextLink
```
<TextLink to={`/users/preview/${i.id}`}>
{getFullName(i)}
</TextLink>
```
=> UIROLES-73: assigned users are not checked when open Pluggable find-user component

src/hooks/useErrorCallout.js, src/hooks/useErrorCallout.test.js
When a react-query request returns non-ok, it passes the resolved fetch as the first argument to its `onError` handler. The previous implementation of `useErrorCallout` did not handle this, and instead naievely expected a string but did not do any input validation.
`callout.sendCallout()`, for its part, _also_ does absolutely zero input validation and, due to its location high in the hierarchy of rendered components, takes down all of Stripes when it fails to render. That ain't great (hence STCOM-1300).
Refs [UIROLES-53](https://folio-org.atlassian.net/browse/UIROLES-53), [STCOM-1300](https://folio-org.atlassian.net/browse/STCOM-1300)
=> UIROLES-53 properly handle react-query 'onError' errors

src/hooks/useRoleCapabilities.js, src/hooks/useRoleCapabilities.test.js, src/hooks/useRoleCapabilitySets.js, src/hooks/useRoleCapabilitySets.test.js, src/settings/components/CreateEditRole/CreateRole.js, src/settings/components/CreateEditRole/EditRole.js, src/settings/components/CreateEditRole/EditRole.test.js
Refs [UIROLES-75. ](https://folio-org.atlassian.net/browse/UIROLES-75)
Instead of fetching all capabilities and capability sets to get the selected applications, just retrieve them from role capabilities and role capability sets. This improvement was noted during the demo of UIROLES-75.
=> UIROLES-75: reduce amount of GET requests by retrieving selected app ids from useRoleCapabilities and useRoleCapabilitySets

src/settings/components/CreateEditRole/EditRole.js
Refs [UIROLES-100](https://folio-org.atlassian.net/browse/UIROLES-100) - Inadvertent clearing of all capabilities/capabilitySets when editing roles.
=> UIROLES-100: disable save and close button on edit unless initial data for capabilities/capabilitySets is loaded

CHANGELOG.md, package.json
`stripes-webpack` compiles bundle assets for applications listed in `stripes.config.js`, but this will ignore shared libraries, i.e. modules that are not applications. Such modules must be listed in `package.json::stripesDeps` in order to tell `stripes-webpack` to gather their assets.
Attn: @alisher-epam 
Refs [UIROLES-102](https://folio-org.atlassian.net/browse/UIROLES-102)
=> UIROLES-102 include stripes-authorization-components assets

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
GitHub recently deprecated v2; v4 is still current. The breaking changes do not impact us.
=> GitHub workflows: update actions/upload-artifact to v4

CHANGELOG.md, src/settings/SettingsPage/SettingsPage.js, src/settings/SettingsPage/SettingsPage.test.js, translations/ui-authorization-roles/en.json
Refs [UIROLES-64](https://folio-org.atlassian.net/browse/UIROLES-64) - Add `Duplicate` authorization role capability for the Authorization role settings.
https://github.com/user-attachments/assets/f708ff10-b196-496d-8904-e0d904c4c241
=> UIROLES-64: Duplicate authorization roles

CHANGELOG.md, package.json
[UIROLES-115](https://folio-org.atlassian.net/browse/UIROLES-115): add missed permission to see list of capabilities set on Edit role page
Permission to see list of capability sets is missed, need to add it into ‘ui-authorization-roles.settings.admin’ permission set.
It will fix request provided in screenshot:
=> UIROLES-115: add missed permission to see list of capabilities set on Edit role page

CHANGELOG.md, package.json, src/index.js, src/settings/SettingsPage/SettingsPage.js
Refs [UIROLES-112](https://folio-org.atlassian.net/browse/UIROLES-112).
=> UIROLES-112: create permissions for CRUD operations

CHANGELOG.md, package.json
- Fulfills [UIROLES-125](https://folio-org.atlassian.net/browse/UIROLES-125).
- Removed unused or duplicate permissions.
- Added new "manage" permission set which allows users to view and assign users to roles.
- Enforcement of "manage" permission is handled in https://github.com/folio-org/stripes-authorization-components/pull/60.
=> [UIROLES-125] Remove unused sub-permissions and add "manage" permission set.

CHANGELOG.md, package.json
- Previously, subpermissions were added to `ui-authorization-roles.settings.view` instead of creating a new permission set `ui-authorization-roles.users.settings.view` in https://github.com/folio-org/ui-authorization-roles/pull/90.
- I went back and combed through [UIROLES-125](https://folio-org.atlassian.net/browse/UIROLES-125) to make sure all permissions are outlined correctly. This is now reflected in the newly added `ui-authorization-roles.users.settings.view` permission set.
=> [UIROLES-125] Add missing "view" assigned users permission set

CHANGELOG.md, src/index.js, src/index.test.js
**Approach**: remove Router from the root of the module, as it creates an internal router scope that prevents navigation to other parts of the application.
=> UIROLES-81: Cannot open user detailed view from role detailed view
